language: node_js
sudo: false
node_js:
  - "9"
  - "8"
  - "6"
  - "4"
matrix:
  allow_failures:
    - node_js: "9"

before_install:
  - curl --location http://rawgit.com/twolfson/fix-travis-ci/master/lib/install.sh | bash -s

notifications:
  email:
    recipients:
      - todd@twolfson.com
    on_success: change
    on_failure: change
